---
- name: Create VM for Windows
  hosts: wintestvm001
  gather_facts: false
  roles:
    - role: azurevm
      delegate_to: localhost
  tags: [vm]

# This play is just a demonstration of doing some action for the VM to see
# that Ansible can manage it.
- name: Install SW on Windows VM
  hosts: wintestvm001
  gather_facts: false
  roles:
    - nodejs-demo
  tags: [conf]
