---
- name: Create VM for Windows
  hosts: wintestvm001
  gather_facts: false
  roles:
    - role: azurevm
      delegate_to: localhost
  tags: [vm]

# This play is just a demonstration of doing some action for the VM to see
# that Ansible can manage it.
- name: Add a user
  hosts: wintestvm001
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: ansible
        password: "@ns1bl3"
        state: present
  tags: [adduser]
